d = {}
Name = input("Enter the Name of the friend :")
Language = input("Enter the name of the language :")
d.update({Name : Language})
Name = input("Enter the Name of the friend :")
Language = input("Enter the name of the language :")
d.update({Name : Language})
Name = input("Enter the Name of the friend :")
Language = input("Enter the name of the language :")
d.update({Name : Language})
Name = input("Enter the Name of the friend :")
Language = input("Enter the name of the language :")
d.update({Name : Language})
print(d)